# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directories: 
      - "/" # Location of package manifests
      - "/app/common"
      - "/app/core"
      - "/app/proprietary"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"

  - package-ecosystem: "docker"
    directory: "/" # Location of Dockerfile
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: "auto"

  - package-ecosystem: npm
    directory: /devTools
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"

  - package-ecosystem: docker
    directory: /docker/backend
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"

  - package-ecosystem: docker
    directory: /docker/embedded
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"

  - package-ecosystem: docker
    directory: /docker/frontend
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"

  - package-ecosystem: cargo
    directory: /frontend/src-tauri
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"

  - package-ecosystem: pip
    directory: /testing/cucumber
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
