[ar_AR]
ignore = [
    'language.direction',
]

[az_AZ]
ignore = [
    'language.direction',
]

[bg_BG]
ignore = [
    'language.direction',
]

[bo_CN]
ignore = [
    'language.direction',
]

[ca_CA]
ignore = [
    'language.direction',
    'watermark.type.1',
]

[cs_CZ]
ignore = [
    'language.direction',
    'text',
]

[da_DK]
ignore = [
    'language.direction',
]

[de_DE]
ignore = [
    'AddStampRequest.alphabet',
    'AddStampRequest.position',
    'alphabet',
    'certSign.name',
    'endpointStatistics.top10',
    'endpointStatistics.top20',
    'fileChooser.dragAndDrop',
    'language.direction',
    'legal.impressum',
    'licenses.version',
    'pipeline.title',
    'pipelineOptions.pipelineHeader',
    'pro',
    'sponsor',
    'text',
    'update.version',
    'validateSignature.cert.version',
    'watermark.type.1',
]

[el_GR]
ignore = [
    'language.direction',
]

[es_ES]
ignore = [
    'language.direction',
    'no',
    'pro',
    'showJS.tags',
    'update.priority.normal',
    'validateSignature.cert.bits',
]

[eu_ES]
ignore = [
    'language.direction',
]

[fa_IR]
ignore = [
    'language.direction',
]

[fr_FR]
ignore = [
    'AddStampRequest.alphabet',
    'AddStampRequest.position',
    'AddStampRequest.rotation',
    'adminUserSettings.actions',
    'alphabet',
    'cookieBanner.preferencesModal.serviceCounterLabel',
    'endpointStatistics.top',
    'endpointStatistics.top10',
    'endpointStatistics.top20',
    'language.direction',
    'licenses.license',
    'licenses.module',
    'licenses.nav',
    'licenses.version',
    'multiTool.page',
    'page',
    'pages',
    'pipeline.title',
    'pro',
    'showJS.tags',
    'update.version',
    'validateSignature.cert.bits',
    'validateSignature.cert.version',
    'validateSignature.date',
    'watermark.type.2',
]

[ga_IE]
ignore = [
    'language.direction',
]

[hi_IN]
ignore = [
    'language.direction',
]

[hr_HR]
ignore = [
    'language.direction',
    'showJS.tags',
]

[hu_HU]
ignore = [
    'endpointStatistics.top10',
    'endpointStatistics.top20',
    'language.direction',
    'pro',
    'showJS.tags',
]

[id_ID]
ignore = [
    'language.direction',
]

[it_IT]
ignore = [
    'language.direction',
    'no',
    'password',
    'pipeline.title',
    'pipelineOptions.pipelineHeader',
    'showJS.tags',
    'sponsor',
]

[ja_JP]
ignore = [
    'language.direction',
]

[ko_KR]
ignore = [
    'language.direction',
]

[ml_IN]
ignore = [
    'lang.iku',
    'language.direction',
]

[ml_ML]
ignore = [
    'language.direction',
]

[nl_NL]
ignore = [
    'language.direction',
    'sponsor',
]

[no_NB]
ignore = [
    'adminUserSettings.admin',
    'info',
    'language.direction',
    'sponsor',
]

[pk_sk]
ignore = [
    'language.direction',
]

[pl_PL]
ignore = [
    'language.direction',
]

[pt_BR]
ignore = [
    'language.direction',
    'pipelineOptions.pipelineHeader',
]

[pt_PT]
ignore = [
    'endpointStatistics.endpoint',
    'endpointStatistics.top',
    'endpointStatistics.top10',
    'endpointStatistics.top20',
    'language.direction',
    'pro',
    'update.priority.normal',
]

[ro_RO]
ignore = [
    'language.direction',
]

[ru_RU]
ignore = [
    'language.direction',
]

[sk_SK]
ignore = [
    'language.direction',
    'text',
    'watermark.type.1',
]

[sl_SI]
ignore = [
    'language.direction',
]

[sr_LATN_RS]
ignore = [
    'endpointStatistics.top',
    'endpointStatistics.top10',
    'endpointStatistics.top20',
    'font',
    'language.direction',
    'pro',
    'showJS.tags',
]

[sv_SE]
ignore = [
    'language.direction',
]

[th_TH]
ignore = [
    'language.direction',
    'showJS.tags',
]

[tr_TR]
ignore = [
    'language.direction',
]

[uk_UA]
ignore = [
    'language.direction',
]

[vi_VN]
ignore = [
    'language.direction',
    'showJS.tags',
]

[zh_BO]
ignore = [
    'language.direction',
]

[zh_CN]
ignore = [
    'language.direction',
]

[zh_TW]
ignore = [
    'language.direction',
    'showJS.tags',
]
