[ar_AR]
ignore = [
    'language.direction',
]

[bg_BG]
ignore = [
    'language.direction',
]

[ca_CA]
ignore = [
    'PDFToText.tags',
    'adminUserSettings.admin',
    'language.direction',
    'survey.button',
    'watermark.type.1',
]

[cs_CZ]
ignore = [
    'info',
    'language.direction',
    'pipeline.header',
    'text',
]

[de_DE]
ignore = [
    'AddStampRequest.alphabet',
    'AddStampRequest.position',
    'PDFToBook.selectText.1',
    'PDFToText.tags',
    'addPageNumbers.selectText.3',
    'alphabet',
    'certSign.name',
    'language.direction',
    'licenses.version',
    'pipeline.title',
    'pipelineOptions.pipelineHeader',
    'sponsor',
    'text',
    'watermark.type.1',
]

[el_GR]
ignore = [
    'language.direction',
]

[es_ES]
ignore = [
    'adminUserSettings.roles',
    'color',
    'error',
    'language.direction',
    'no',
    'showJS.tags',
]

[eu_ES]
ignore = [
    'language.direction',
]

[fr_FR]
ignore = [
    'AddStampRequest.alphabet',
    'AddStampRequest.position',
    'AddStampRequest.rotation',
    'PDFToBook.selectText.1',
    'addPageNumbers.selectText.3',
    'adminUserSettings.actions',
    'alphabet',
    'compare.document.1',
    'compare.document.2',
    'info',
    'language.direction',
    'licenses.license',
    'licenses.module',
    'licenses.nav',
    'licenses.version',
    'pdfOrganiser.mode',
    'pipeline.title',
    'pipelineOptions.pipelineHeader',
    'sponsor',
    'watermark.type.2',
]

[hi_IN]
ignore = [
    'language.direction',
]

[hr_HR]
ignore = [
    'PDFToBook.selectText.1',
    'font',
    'home.pipeline.title',
    'info',
    'language.direction',
    'pdfOrganiser.tags',
    'showJS.tags',
]

[hu_HU]
ignore = [
    'language.direction',
]

[id_ID]
ignore = [
    'language.direction',
]

[it_IT]
ignore = [
    'font',
    'language.direction',
    'no',
    'password',
    'pipeline.title',
    'pipelineOptions.pipelineHeader',
    'removePassword.selectText.2',
    'showJS.tags',
    'sponsor',
]

[ja_JP]
ignore = [
    'language.direction',
]

[ko_KR]
ignore = [
    'language.direction',
]

[nl_NL]
ignore = [
    'HTMLToPDF.print',
    'adjustContrast.contrast',
    'compare.document.1',
    'compare.document.2',
    'error',
    'getPdfInfo.downloadJson',
    'help',
    'info',
    'language.direction',
    'navbar.allTools',
    'printFile.submit',
    'showJS.downloadJS',
    'sponsor',
]

[no_NB]
ignore = [
    'PDFToBook.selectText.1',
    'adminUserSettings.admin',
    'info',
    'language.direction',
    'oops',
    'sponsor',
]

[pl_PL]
ignore = [
    'PDFToBook.selectText.1',
    'language.direction',
]

[pt_BR]
ignore = [
    'language.direction',
]

[pt_PT]
ignore = [
    'language.direction',
]

[ro_RO]
ignore = [
    'language.direction',
]

[ru_RU]
ignore = [
    'language.direction',
]

[sk_SK]
ignore = [
    'adminUserSettings.admin',
    'home.multiTool.title',
    'info',
    'language.direction',
    'navbar.sections.security',
    'text',
    'watermark.type.1',
]

[sr_LATN_RS]
ignore = [
    'language.direction',
    'licenses.version',
    'poweredBy',
]

[sv_SE]
ignore = [
    'language.direction',
]

[th_TH]
ignore = [
    'language.direction',
    'pipeline.title',
    'pipelineOptions.pipelineHeader',
    'showJS.tags',
]

[tr_TR]
ignore = [
    'language.direction',
]

[uk_UA]
ignore = [
    'language.direction',
]

[zh_CN]
ignore = [
    'language.direction',
]

[zh_TW]
ignore = [
    'language.direction',
]
