[ar_AR]
ignore = [
    'lang.div',
    'lang.dzo',
    'lang.que',
    'language.direction',
]

[az_AZ]
ignore = [
    'lang.afr',
    'lang.bre',
    'lang.div',
    'lang.epo',
    'lang.guj',
    'lang.hin',
    'lang.kan',
    'lang.mal',
    'lang.mar',
    'lang.mlt',
    'lang.mri',
    'lang.msa',
    'lang.nep',
    'lang.ori',
    'lang.pan',
    'lang.san',
    'lang.sin',
    'lang.slk',
    'lang.snd',
    'lang.sun',
    'lang.tam',
    'lang.tat',
    'lang.urd',
    'lang.yor',
    'language.direction',
]

[bg_BG]
ignore = [
    'lang.div',
    'lang.dzo',
    'lang.iku',
    'lang.que',
    'language.direction',
]

[bo_CN]
ignore = [
    'language.direction',
]

[ca_CA]
ignore = [
    'adminUserSettings.admin',
    'lang.amh',
    'lang.ceb',
    'lang.chr',
    'lang.div',
    'lang.dzo',
    'lang.epo',
    'lang.fao',
    'lang.fry',
    'lang.guj',
    'lang.hin',
    'lang.iku',
    'lang.kan',
    'lang.kaz',
    'lang.lao',
    'lang.mar',
    'lang.mri',
    'lang.ori',
    'lang.pan',
    'lang.pus',
    'lang.que',
    'lang.snd',
    'lang.swa',
    'lang.tam',
    'lang.tat',
    'lang.tel',
    'lang.tgk',
    'lang.tgl',
    'lang.tir',
    'lang.uzb',
    'lang.uzb_cyrl',
    'language.direction',
    'watermark.type.1',
]

[cs_CZ]
ignore = [
    'lang.amh',
    'lang.asm',
    'lang.bod',
    'lang.bos',
    'lang.bre',
    'lang.ceb',
    'lang.chr',
    'lang.div',
    'lang.dzo',
    'lang.frk',
    'lang.gla',
    'lang.guj',
    'lang.iku',
    'lang.jav',
    'lang.kan',
    'lang.kat',
    'lang.khm',
    'lang.kir',
    'lang.lao',
    'lang.mal',
    'lang.mar',
    'lang.mri',
    'lang.msa',
    'lang.nor',
    'lang.oci',
    'lang.ori',
    'lang.pan',
    'lang.pus',
    'lang.que',
    'lang.san',
    'lang.sin',
    'lang.snd',
    'lang.sun',
    'lang.tam',
    'lang.tat',
    'lang.tel',
    'lang.tgl',
    'lang.tha',
    'lang.tir',
    'lang.uig',
    'lang.urd',
    'lang.uzb',
    'lang.uzb_cyrl',
    'lang.yor',
    'language.direction',
    'text',
]

[da_DK]
ignore = [
    'lang.afr',
    'lang.amh',
    'lang.ben',
    'lang.bre',
    'lang.ceb',
    'lang.chr',
    'lang.div',
    'lang.dzo',
    'lang.epo',
    'lang.frk',
    'lang.guj',
    'lang.hin',
    'lang.iku',
    'lang.jav',
    'lang.kan',
    'lang.khm',
    'lang.lao',
    'lang.lat',
    'lang.ltz',
    'lang.mal',
    'lang.mar',
    'lang.mri',
    'lang.msa',
    'lang.nep',
    'lang.oci',
    'lang.ori',
    'lang.pan',
    'lang.pus',
    'lang.que',
    'lang.san',
    'lang.sin',
    'lang.slk_frak',
    'lang.snd',
    'lang.sun',
    'lang.swa',
    'lang.tam',
    'lang.tat',
    'lang.tel',
    'lang.tgk',
    'lang.tgl',
    'lang.tha',
    'lang.tir',
    'lang.ton',
    'lang.uig',
    'lang.urd',
    'lang.uzb',
    'lang.yor',
    'language.direction',
]

[de_DE]
ignore = [
    'AddStampRequest.alphabet',
    'AddStampRequest.position',
    'PDFToBook.selectText.1',
    'PDFToText.tags',
    'addPageNumbers.selectText.3',
    'adminUserSettings.team',
    'alphabet',
    'audit.dashboard.modal.id',
    'audit.dashboard.status',
    'audit.dashboard.tab.dashboard',
    'audit.dashboard.tab.export',
    'audit.dashboard.table.details',
    'audit.dashboard.table.id',
    'certSign.name',
    'cookieBanner.popUp.acceptAllBtn',
    'endpointStatistics.top10',
    'endpointStatistics.top20',
    'fileChooser.dragAndDrop',
    'home.pipeline.title',
    'lang.afr',
    'lang.ceb',
    'lang.chr',
    'lang.div',
    'lang.dzo',
    'lang.epo',
    'lang.guj',
    'lang.hin',
    'lang.iku',
    'lang.kan',
    'lang.mal',
    'lang.mar',
    'lang.mri',
    'lang.nep',
    'lang.ori',
    'lang.pan',
    'lang.que',
    'lang.san',
    'lang.snd',
    'lang.tam',
    'lang.tel',
    'lang.tgl',
    'lang.tir',
    'lang.urd',
    'lang.yor',
    'language.direction',
    'legal.impressum',
    'licenses.version',
    'pipeline.title',
    'pipelineOptions.pipelineHeader',
    'pro',
    'redact.zoom',
    'scannerEffect.quality.medium',
    'sponsor',
    'team.status',
    'text',
    'validateSignature.cert.bits',
    'validateSignature.cert.version',
    'validateSignature.status',
    'watermark.type.1',
]

[el_GR]
ignore = [
    'lang.ceb',
    'lang.dzo',
    'lang.iku',
    'lang.ori',
    'lang.pan',
    'lang.que',
    'lang.sin',
    'lang.uig',
    'lang.uzb_cyrl',
    'language.direction',
]

[es_ES]
ignore = [
    'error',
    'lang.asm',
    'lang.ceb',
    'lang.chr',
    'lang.div',
    'lang.dzo',
    'lang.fil',
    'lang.frm',
    'lang.guj',
    'lang.iku',
    'lang.kan',
    'lang.lao',
    'lang.mal',
    'lang.mar',
    'lang.oci',
    'lang.ori',
    'lang.pan',
    'lang.san',
    'lang.snd',
    'lang.sun',
    'lang.tam',
    'lang.tel',
    'lang.tir',
    'lang.urd',
    'lang.uzb',
    'lang.yor',
    'language.direction',
    'no',
    'showJS.tags',
]

[eu_ES]
ignore = [
    'lang.ceb',
    'lang.chr',
    'lang.div',
    'lang.dzo',
    'lang.guj',
    'lang.iku',
    'lang.kan',
    'lang.mal',
    'lang.pan',
    'lang.que',
    'lang.san',
    'lang.slv',
    'lang.snd',
    'lang.sqi',
    'lang.tat',
    'lang.tir',
    'lang.yor',
    'language.direction',
]

[fa_IR]
ignore = [
    'language.direction',
]

[fr_FR]
ignore = [
    'AddStampRequest.alphabet',
    'AddStampRequest.position',
    'AddStampRequest.rotation',
    'PDFToBook.selectText.1',
    'addPageNumbers.selectText.3',
    'adminUserSettings.actions',
    'alphabet',
    'compare.document.1',
    'compare.document.2',
    'lang.bre',
    'lang.ceb',
    'lang.chr',
    'lang.div',
    'lang.dzo',
    'lang.eus',
    'lang.guj',
    'lang.iku',
    'lang.kan',
    'lang.kaz',
    'lang.khm',
    'lang.lao',
    'lang.ltz',
    'lang.mal',
    'lang.mar',
    'lang.oci',
    'lang.ori',
    'lang.que',
    'lang.san',
    'lang.snd',
    'lang.swa',
    'lang.tel',
    'lang.tgl',
    'lang.tir',
    'lang.yor',
    'language.direction',
    'licenses.license',
    'licenses.module',
    'licenses.nav',
    'licenses.version',
    'pdfOrganiser.mode',
    'pipeline.title',
    'watermark.type.2',
]

[ga_IE]
ignore = [
    'lang.ceb',
    'lang.cos',
    'lang.div',
    'lang.dzo',
    'lang.epo',
    'lang.guj',
    'lang.hat',
    'lang.iku',
    'lang.lao',
    'lang.oci',
    'lang.ori',
    'lang.pan',
    'lang.sin',
    'lang.snd',
    'lang.sun',
    'lang.tgk',
    'lang.tir',
    'lang.uig',
    'language.direction',
]

[hi_IN]
ignore = [
    'language.direction',
]

[hr_HR]
ignore = [
    'PDFToBook.selectText.1',
    'home.pipeline.title',
    'lang.bod',
    'lang.bre',
    'lang.ceb',
    'lang.chr',
    'lang.dzo',
    'lang.guj',
    'lang.iku',
    'lang.kan',
    'lang.lao',
    'lang.mri',
    'lang.ori',
    'lang.pan',
    'lang.pus',
    'lang.que',
    'lang.san',
    'lang.snd',
    'lang.tam',
    'lang.tel',
    'lang.tgl',
    'lang.tir',
    'language.direction',
    'showJS.tags',
]

[hu_HU]
ignore = [
    'audit.dashboard.export.json',
    'audit.dashboard.modal.id',
    'audit.dashboard.table.id',
    'endpointStatistics.top10',
    'endpointStatistics.top20',
    'home.pipeline.title',
    'language.direction',
    'pipeline.title',
    'pipelineOptions.pipelineHeader',
    'pro',
    'showJS.tags',
]

[id_ID]
ignore = [
    'lang.aze',
    'lang.aze_cyrl',
    'lang.bre',
    'lang.cat',
    'lang.ceb',
    'lang.chr',
    'lang.cym',
    'lang.div',
    'lang.dzo',
    'lang.epo',
    'lang.eus',
    'lang.fao',
    'lang.frk',
    'lang.guj',
    'lang.hin',
    'lang.iku',
    'lang.kan',
    'lang.kaz',
    'lang.kir',
    'lang.lao',
    'lang.lat',
    'lang.mal',
    'lang.mar',
    'lang.mri',
    'lang.ori',
    'lang.pan',
    'lang.pus',
    'lang.que',
    'lang.slk_frak',
    'lang.snd',
    'lang.sun',
    'lang.swa',
    'lang.tam',
    'lang.tat',
    'lang.tel',
    'lang.tgk',
    'lang.tgl',
    'lang.tha',
    'lang.tir',
    'lang.uig',
    'lang.urd',
    'lang.uzb',
    'lang.uzb_cyrl',
    'lang.yor',
    'language.direction',
]

[it_IT]
ignore = [
    'lang.asm',
    'lang.ceb',
    'lang.chr',
    'lang.div',
    'lang.dzo',
    'lang.fao',
    'lang.guj',
    'lang.iku',
    'lang.kan',
    'lang.lao',
    'lang.mal',
    'lang.mar',
    'lang.mri',
    'lang.ori',
    'lang.pan',
    'lang.pus',
    'lang.que',
    'lang.snd',
    'lang.swa',
    'lang.tam',
    'lang.tel',
    'lang.tgl',
    'lang.urd',
    'lang.yor',
    'language.direction',
    'no',
    'password',
    'pipeline.title',
    'pipelineOptions.pipelineHeader',
    'removePassword.selectText.2',
    'showJS.tags',
    'sponsor',
]

[ja_JP]
ignore = [
    'language.direction',
]

[ko_KR]
ignore = [
    'lang.fao',
    'lang.pus',
    'lang.sun',
    'language.direction',
]

[ml_IN]
ignore = [
    'lang.iku',
    'language.direction',
]

[nl_NL]
ignore = [
    'compare.document.1',
    'compare.document.2',
    'lang.afr',
    'lang.asm',
    'lang.bre',
    'lang.ceb',
    'lang.chr',
    'lang.dzo',
    'lang.epo',
    'lang.fao',
    'lang.guj',
    'lang.hin',
    'lang.iku',
    'lang.kan',
    'lang.lao',
    'lang.mal',
    'lang.mar',
    'lang.mri',
    'lang.oci',
    'lang.ori',
    'lang.pan',
    'lang.pus',
    'lang.que',
    'lang.sin',
    'lang.snd',
    'lang.sun',
    'lang.swa',
    'lang.tam',
    'lang.tel',
    'lang.tgl',
    'lang.ton',
    'lang.urd',
    'lang.yor',
    'language.direction',
    'navbar.allTools',
    'sponsor',
]

[no_NB]
ignore = [
    'PDFToBook.selectText.1',
    'adminUserSettings.admin',
    'info',
    'lang.afr',
    'lang.amh',
    'lang.ben',
    'lang.bos',
    'lang.bre',
    'lang.ceb',
    'lang.chr',
    'lang.dan_frak',
    'lang.div',
    'lang.dzo',
    'lang.epo',
    'lang.guj',
    'lang.hin',
    'lang.iku',
    'lang.kan',
    'lang.khm',
    'lang.lao',
    'lang.lat',
    'lang.ltz',
    'lang.mal',
    'lang.mar',
    'lang.mri',
    'lang.msa',
    'lang.nep',
    'lang.ori',
    'lang.pan',
    'lang.pus',
    'lang.que',
    'lang.san',
    'lang.slk_frak',
    'lang.snd',
    'lang.swa',
    'lang.tam',
    'lang.tat',
    'lang.tel',
    'lang.tgk',
    'lang.tgl',
    'lang.tha',
    'lang.tir',
    'lang.ton',
    'lang.uig',
    'lang.urd',
    'lang.yor',
    'language.direction',
    'oops',
    'sponsor',
]

[pl_PL]
ignore = [
    'PDFToBook.selectText.1',
    'lang.afr',
    'lang.bre',
    'lang.ceb',
    'lang.chr',
    'lang.cos',
    'lang.div',
    'lang.dzo',
    'lang.fao',
    'lang.frk',
    'lang.guj',
    'lang.hat',
    'lang.iku',
    'lang.kan',
    'lang.khm',
    'lang.lao',
    'lang.mal',
    'lang.mar',
    'lang.mri',
    'lang.nep',
    'lang.oci',
    'lang.ori',
    'lang.pus',
    'lang.que',
    'lang.snd',
    'lang.sun',
    'lang.swa',
    'lang.tam',
    'lang.tat',
    'lang.tel',
    'lang.tgl',
    'lang.tir',
    'lang.uig',
    'lang.urd',
    'language.direction',
]

[pt_BR]
ignore = [
    'lang.bre',
    'lang.ceb',
    'lang.chr',
    'lang.div',
    'lang.dzo',
    'lang.fao',
    'lang.fil',
    'lang.frk',
    'lang.fry',
    'lang.guj',
    'lang.iku',
    'lang.kan',
    'lang.kir',
    'lang.mar',
    'lang.ori',
    'lang.pan',
    'lang.que',
    'lang.snd',
    'lang.tat',
    'lang.tel',
    'lang.tgl',
    'lang.tir',
    'lang.uig',
    'lang.uzb',
    'lang.yid',
    'language.direction',
    'pipelineOptions.pipelineHeader',
]

[pt_PT]
ignore = [
    'lang.bre',
    'lang.ceb',
    'lang.chr',
    'lang.div',
    'lang.dzo',
    'lang.fao',
    'lang.fil',
    'lang.frk',
    'lang.fry',
    'lang.guj',
    'lang.iku',
    'lang.kan',
    'lang.kir',
    'lang.mar',
    'lang.ori',
    'lang.pan',
    'lang.que',
    'lang.snd',
    'lang.tat',
    'lang.tel',
    'lang.tgl',
    'lang.tir',
    'lang.uig',
    'lang.uzb',
    'lang.yid',
    'language.direction',
]

[ro_RO]
ignore = [
    'lang.amh',
    'lang.asm',
    'lang.bod',
    'lang.bre',
    'lang.ceb',
    'lang.chr',
    'lang.cos',
    'lang.deu_frak',
    'lang.div',
    'lang.dzo',
    'lang.est',
    'lang.fao',
    'lang.glg',
    'lang.guj',
    'lang.iku',
    'lang.jav',
    'lang.kan',
    'lang.lao',
    'lang.mal',
    'lang.mar',
    'lang.mri',
    'lang.nep',
    'lang.oci',
    'lang.ori',
    'lang.pan',
    'lang.pus',
    'lang.slk_frak',
    'lang.snd',
    'lang.sun',
    'lang.swa',
    'lang.tam',
    'lang.tel',
    'lang.tgl',
    'lang.tir',
    'lang.urd',
    'lang.yor',
    'language.direction',
]

[ru_RU]
ignore = [
    'lang.iku',
    'lang.pus',
    'language.direction',
]

[sk_SK]
ignore = [
    'adminUserSettings.admin',
    'home.multiTool.title',
    'info',
    'lang.ceb',
    'lang.chr',
    'lang.dzo',
    'lang.epo',
    'lang.iku',
    'lang.kaz',
    'lang.mar',
    'lang.ori',
    'lang.pan',
    'lang.que',
    'lang.san',
    'lang.sin',
    'lang.snd',
    'lang.tat',
    'lang.tel',
    'lang.tgl',
    'lang.tir',
    'lang.urd',
    'lang.uzb',
    'language.direction',
    'navbar.sections.security',
    'text',
    'watermark.type.1',
]

[sl_SI]
ignore = [
    'lang.bre',
    'lang.ceb',
    'lang.chr',
    'lang.div',
    'lang.dzo',
    'lang.epo',
    'lang.eus',
    'lang.fao',
    'lang.frk',
    'lang.guj',
    'lang.iku',
    'lang.kan',
    'lang.lao',
    'lang.mar',
    'lang.mri',
    'lang.oci',
    'lang.ori',
    'lang.pan',
    'lang.que',
    'lang.slk',
    'lang.snd',
    'lang.sun',
    'lang.tam',
    'lang.tat',
    'lang.tel',
    'lang.tgk',
    'lang.tgl',
    'lang.tir',
    'lang.urd',
    'lang.uzb',
    'lang.yor',
    'language.direction',
]

[sr_LATN_RS]
ignore = [
    'audit.dashboard.modal.id',
    'audit.dashboard.status',
    'audit.dashboard.table.id',
    'endpointStatistics.top',
    'endpointStatistics.top10',
    'endpointStatistics.top20',
    'font',
    'info',
    'lang.div',
    'lang.epo',
    'lang.hin',
    'lang.iku',
    'lang.mar',
    'lang.san',
    'lang.snd',
    'lang.tel',
    'lang.tgl',
    'lang.urd',
    'language.direction',
    'pro',
    'showJS.tags',
    'team.status',
    'validateSignature.status',
]

[sv_SE]
ignore = [
    'lang.ben',
    'lang.bre',
    'lang.ceb',
    'lang.chr',
    'lang.dzo',
    'lang.epo',
    'lang.guj',
    'lang.hin',
    'lang.kan',
    'lang.lao',
    'lang.lat',
    'lang.mal',
    'lang.mri',
    'lang.ori',
    'lang.pan',
    'lang.que',
    'lang.san',
    'lang.slk_frak',
    'lang.snd',
    'lang.tam',
    'lang.tat',
    'lang.tel',
    'lang.tir',
    'lang.urd',
    'lang.yor',
    'language.direction',
]

[th_TH]
ignore = [
    'lang.dzo',
    'lang.kir',
    'lang.pan',
    'lang.sin',
    'lang.slk_frak',
    'lang.tir',
    'lang.uzb_cyrl',
    'language.direction',
    'pipelineOptions.pipelineHeader',
    'showJS.tags',
]

[tr_TR]
ignore = [
    'lang.afr',
    'lang.bre',
    'lang.ceb',
    'lang.chr',
    'lang.div',
    'lang.dzo',
    'lang.epo',
    'lang.fao',
    'lang.guj',
    'lang.kan',
    'lang.lao',
    'lang.mal',
    'lang.mar',
    'lang.mri',
    'lang.msa',
    'lang.ori',
    'lang.pus',
    'lang.que',
    'lang.sin',
    'lang.slk',
    'lang.slk_frak',
    'lang.snd',
    'lang.tam',
    'lang.tat',
    'lang.tel',
    'lang.tgk',
    'lang.tgl',
    'lang.tir',
    'lang.urd',
    'lang.yor',
    'language.direction',
]

[uk_UA]
ignore = [
    'lang.iku',
    'language.direction',
]

[vi_VN]
ignore = [
    'lang.amh',
    'lang.asm',
    'lang.aze',
    'lang.aze_cyrl',
    'lang.bos',
    'lang.bre',
    'lang.cat',
    'lang.ceb',
    'lang.chr',
    'lang.cos',
    'lang.div',
    'lang.dzo',
    'lang.epo',
    'lang.eus',
    'lang.fao',
    'lang.glg',
    'lang.guj',
    'lang.iku',
    'lang.kan',
    'lang.kaz',
    'lang.kir',
    'lang.lat',
    'lang.ltz',
    'lang.mal',
    'lang.mar',
    'lang.mri',
    'lang.msa',
    'lang.ori',
    'lang.pus',
    'lang.que',
    'lang.sin',
    'lang.slk',
    'lang.slk_frak',
    'lang.snd',
    'lang.swa',
    'lang.syr',
    'lang.tam',
    'lang.tat',
    'lang.tel',
    'lang.tgk',
    'lang.tir',
    'lang.uig',
    'lang.uzb',
    'lang.uzb_cyrl',
    'lang.yid',
    'lang.yor',
    'language.direction',
    'pipeline.title',
    'pipelineOptions.pipelineHeader',
    'showJS.tags',
]

[zh_CN]
ignore = [
    'language.direction',
]

[zh_TW]
ignore = [
    'language.direction',
    'poweredBy',
    'showJS.tags',
]
