[ar_AR]
ignore = [
    'language.direction',
]

[az_AZ]
ignore = [
    'language.direction',
]

[bg_BG]
ignore = [
    'language.direction',
]

[bo_CN]
ignore = [
    'admin.settings.advanced.processExecutor.libreOffice',
    'admin.settings.advanced.processExecutor.ocrMyPdf',
    'admin.settings.advanced.processExecutor.qpdf',
    'admin.settings.advanced.processExecutor.tesseract',
    'admin.settings.connections.oauth2.label',
    'admin.settings.connections.saml2.label',
    'convert.dpi',
    'endpointStatistics.dataTypeApi',
    'getPdfInfo.other.javaScript',
    'getPdfInfo.other.xmp',
    'getPdfInfo.summary.tech.javaScript',
    'home.devApi.title',
    'language.direction',
    'removeBlanks.whitePercent.unit',
    'showJS.tags',
    'usage.controls.dataType.api',
    'validateSignature.downloadType.csv',
    'validateSignature.downloadType.json',
    'validateSignature.downloadType.pdf',
]

[ca_CA]
ignore = [
    'language.direction',
    'watermark.type.1',
]

[cs_CZ]
ignore = [
    'language.direction',
    'text',
]

[da_DK]
ignore = [
    'language.direction',
]

[de_DE]
ignore = [
    'AddStampRequest.alphabet',
    'AddStampRequest.position',
    'adjustPageScale.pageSize.legal',
    'adjustPageScale.pageSize.letter',
    'admin.settings.advanced.processExecutor.calibre',
    'admin.settings.advanced.processExecutor.ghostscript',
    'admin.settings.advanced.processExecutor.libreOffice',
    'admin.settings.advanced.processExecutor.ocrMyPdf',
    'admin.settings.advanced.processExecutor.pythonOpenCv',
    'admin.settings.advanced.processExecutor.qpdf',
    'admin.settings.advanced.processExecutor.tesseract',
    'admin.settings.advanced.processExecutor.weasyPrint',
    'admin.settings.connections.oauth2.label',
    'admin.settings.connections.saml2.label',
    'admin.settings.database.port.label',
    'admin.settings.general.logoStyle.modern',
    'admin.settings.general.system',
    'admin.settings.legal.impressum.label',
    'admin.settings.premium.title',
    'alphabet',
    'annotation.contents',
    'annotation.ellipse',
    'annotation.polygon',
    'audit.events.details',
    'audit.tabs.dashboard',
    'audit.tabs.export',
    'certSign.logoTitle',
    'certSign.name',
    'common.save',
    'convert.dpi',
    'convert.markdown',
    'convert.pptExt',
    'convert.rtfExt',
    'convert.textRtf',
    'cookieBanner.services.posthog',
    'cookieBanner.services.scarf',
    'crop.autoCrop',
    'details',
    'endpointStatistics.dataTypeApi',
    'endpointStatistics.dataTypeUi',
    'endpointStatistics.top10',
    'endpointStatistics.top20',
    'fileChooser.dragAndDrop',
    'fileManager.fileFormat',
    'fileManager.fileName',
    'fileManager.fileVersion',
    'fileManager.googleDrive',
    'fileManager.googleDriveShort',
    'footer.discord',
    'footer.issues',
    'getPdfInfo.downloads',
    'getPdfInfo.indexTitle',
    'getPdfInfo.other.javaScript',
    'getPdfInfo.other.xmp',
    'getPdfInfo.perPage.links',
    'getPdfInfo.perPage.multimedia',
    'getPdfInfo.sections.compliance',
    'getPdfInfo.summary.tech.javaScript',
    'getPdfInfo.summary.tech.multimedia',
    'home.devApi.title',
    'language.direction',
    'legal.impressum',
    'licenses.version',
    'login.debug',
    'pdfTextEditor.options.advanced.title',
    'pipeline.title',
    'pipelineOptions.pipelineHeader',
    'plan.enterprise.name',
    'plan.pro.name',
    'plan.upgrade',
    'pro',
    'quickAccess.reader',
    'redact.manual.zoom',
    'removeBlanks.whitePercent.unit',
    'rightRail.annotations',
    'settings.connection.mode.saas',
    'settings.connection.server',
    'settings.licensingAnalytics.audit',
    'settings.licensingAnalytics.plan',
    'settings.workspace.teams',
    'setup.mode.saas.title',
    'setup.server.type.saas',
    'sign.saved.type.text',
    'sign.type.text',
    'signup.name',
    'sponsor',
    'text',
    'toolPanel.alpha',
    'update.priority.normal',
    'update.version',
    'usage.controls.dataType.api',
    'usage.controls.dataType.ui',
    'usage.controls.top10',
    'usage.controls.top20',
    'usage.showing.top10',
    'usage.showing.top20',
    'validateSignature.cert.version',
    'validateSignature.downloadType.csv',
    'validateSignature.downloadType.json',
    'validateSignature.downloadType.pdf',
    'validateSignature.report.downloads',
    'validateSignature.status._value',
    'watermark.type.1',
    'watermark.watermarkType.text',
    'workspace.people.actions.upgrade',
    'workspace.people.addMember.usernamePlaceholder',
    'workspace.people.admin',
    'workspace.people.emailInvite.emailsPlaceholder',
    'workspace.people.inviteLink.emailPlaceholder',
    'workspace.people.inviteMode.link',
    'workspace.people.status',
    'workspace.people.team',
    'workspace.teams.system',
    'workspace.teams.title',
]

[el_GR]
ignore = [
    'language.direction',
]

[es_ES]
ignore = [
    'language.direction',
    'no',
    'pro',
    'showJS.tags',
    'update.priority.normal',
    'validateSignature.cert.bits',
]

[eu_ES]
ignore = [
    'language.direction',
]

[fa_IR]
ignore = [
    'language.direction',
]

[fr_FR]
ignore = [
    'AddStampRequest.alphabet',
    'AddStampRequest.position',
    'AddStampRequest.rotation',
    'adminUserSettings.actions',
    'alphabet',
    'cookieBanner.preferencesModal.serviceCounterLabel',
    'endpointStatistics.top',
    'endpointStatistics.top10',
    'endpointStatistics.top20',
    'language.direction',
    'licenses.license',
    'licenses.module',
    'licenses.nav',
    'licenses.version',
    'multiTool.page',
    'page',
    'pages',
    'pipeline.title',
    'pro',
    'showJS.tags',
    'update.version',
    'validateSignature.cert.bits',
    'validateSignature.cert.version',
    'validateSignature.date',
    'watermark.type.2',
]

[ga_IE]
ignore = [
    'language.direction',
]

[hi_IN]
ignore = [
    'language.direction',
]

[hr_HR]
ignore = [
    'language.direction',
    'showJS.tags',
]

[hu_HU]
ignore = [
    'endpointStatistics.top10',
    'endpointStatistics.top20',
    'language.direction',
    'pro',
    'showJS.tags',
]

[id_ID]
ignore = [
    'language.direction',
]

[it_IT]
ignore = [
    'language.direction',
    'no',
    'password',
    'pipeline.title',
    'pipelineOptions.pipelineHeader',
    'showJS.tags',
    'sponsor',
]

[ja_JP]
ignore = [
    'language.direction',
]

[ko_KR]
ignore = [
    'language.direction',
]

[ml_IN]
ignore = [
    'lang.iku',
    'language.direction',
]

[ml_ML]
ignore = [
    'language.direction',
]

[nl_NL]
ignore = [
    'language.direction',
    'sponsor',
]

[no_NB]
ignore = [
    'adminUserSettings.admin',
    'info',
    'language.direction',
    'sponsor',
]

[pk_sk]
ignore = [
    'language.direction',
]

[pl_PL]
ignore = [
    'language.direction',
]

[pt_BR]
ignore = [
    'language.direction',
    'pipelineOptions.pipelineHeader',
]

[pt_PT]
ignore = [
    'endpointStatistics.endpoint',
    'endpointStatistics.top',
    'endpointStatistics.top10',
    'endpointStatistics.top20',
    'language.direction',
    'pro',
    'update.priority.normal',
]

[ro_RO]
ignore = [
    'language.direction',
]

[ru_RU]
ignore = [
    'language.direction',
]

[sk_SK]
ignore = [
    'language.direction',
    'text',
    'watermark.type.1',
]

[sl_SI]
ignore = [
    'language.direction',
]

[sr_LATN_RS]
ignore = [
    'endpointStatistics.top',
    'endpointStatistics.top10',
    'endpointStatistics.top20',
    'font',
    'language.direction',
    'pro',
    'showJS.tags',
]

[sv_SE]
ignore = [
    'language.direction',
]

[th_TH]
ignore = [
    'language.direction',
    'showJS.tags',
]

[tr_TR]
ignore = [
    'language.direction',
]

[uk_UA]
ignore = [
    'language.direction',
]

[vi_VN]
ignore = [
    'language.direction',
    'showJS.tags',
]

[zh_BO]
ignore = [
    'language.direction',
]

[zh_CN]
ignore = [
    'language.direction',
]

[zh_TW]
ignore = [
    'language.direction',
    'showJS.tags',
]
